---
# Copyright 2024 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Get install_yamls
  ansible.builtin.shell:
    chdir: "~"
    cmd: git clone {{ install_yamls_source }}
    creates: "~/install_yamls"
  register: setup_rhelai_packages_download
  until: setup_rhelai_packages_download is succeeded
  retries: "{{ setup_rhelai_download_retries }}"
  delay: "{{ setup_rhelai_download_delay }}"

- name: Checkout selected commit
  ansible.builtin.shell:
    chdir: "~/install_yamls"
    cmd: git checkout {{ install_yamls_commit_hash }}

# Download tools unless there is a flag file present
- name: Run download_tools target
  ansible.builtin.shell:
    chdir: "~/install_yamls/devsetup"
    cmd: make download_tools && touch ./tools_installed
    creates: ./tools_installed
  register: setup_rhelai_packages_download
  until: setup_rhelai_packages_download is succeeded
  retries: "{{ setup_rhelai_download_retries }}"
  delay: "{{ setup_rhelai_download_delay }}"